version: "3"
services:
  db:
    build: ./postgres
    ports:
      - 5432:5432
    environment:
     POSTGRES_HOST_AUTH_METHOD: trust
  handle:
    build: ./handle
    ports:
      - 2641:2641/tcp
      - 2641:2641/udp
      - 8000:8000
    depends_on:
      - db