#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $HANDLE_ACCOUNT_ADMIN WITH PASSWORD '$HANDLE_ACCOUNT_PASSW';
    CREATE DATABASE "$HANDLE_DATABASE_NAME";
    GRANT ALL PRIVILEGES ON DATABASE "$HANDLE_DATABASE_NAME" TO $HANDLE_ACCOUNT_ADMIN;
EOSQL
