#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $POSTGRES_DBUSER WITH PASSWORD '$POSTGRES_DBPASS';
    CREATE DATABASE "$POSTGRES_DBNAME";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DBNAME" TO $POSTGRES_DBUSER;
EOSQL